name: bookihub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_native_splash: ^2.3.4
  flutter_phone_direct_caller: ^2.1.1
  flutter_polyline_points: ^2.0.0
  font_awesome_flutter: ^10.6.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  dartz: ^0.10.1
  provider: ^6.0.5
  intl: ^0.18.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: font\Inter-VariableFont_slnt,wght.ttf
